window.BOSS_LOCATIONS = {
  "harit guardian garangky": "Hunters",
  "roaring lord kastor": "Aden",
  "archon suscepter": "Dion",
  "death lord hallate": "Aden",
  "ghost of peasant leader": "Aden",
  "gwindorr": "Heine",
  "eye of beleth": "Dion",
  "guilotine warden of the execution grounds": "Dion",
  "zombie lord crowl": "Gludio",
  "fairy queen timiniel": "Hunters",
  "krokian padisha sobekk": "Giran",
  "agent of beres meana": "Giran",
  "orfen": "Oren",
  "patriarch kuroboros": "Gludin",
  "taik high prefect arak": "Aden",
  "karte": "Aden",
  "shaman king selu": "Oren",
  "palibati queen themis": "Aden",
  "daimon the white-eyed": "Goddard",
  "liliths witch marilion": "Giran",
  "varkas chief horus": "Goddard",
  "high priestess van halter": "Rune",
  "shilens priest hisilrome": "Aden",
  "death lord shax": "Aden",
  "unrequited kael": "Gludin",
  "uruka": "Rune",
  "queen shyeed": "Rune",
  "shadow of halisha b id 25342": "Goddard",
  "antharas": "Giran",
  "storm winged naga": "Aden",
  "timak orc gosmos": "Oren",
  "anakims nemesis zakaron": "Hunters",
  "core": "Dion",
  "water spirit lian": "Heine",
  "fire of wrath shuriel": "Aden",
  "remmel": "Dion",
  "tiger hornet": "Dion",
  "varkas commander mos": "Goddard",
  "skyla": "Giran",
  "enmity ghost ramdal": "Aden",
  "cherub galaxia": "Aden",
  "abyss brukunt": "Hunters",
  "evil spirit tempest": "Dion",
  "sebek": "Heine",
  "red eye captain trakia": "Dion",
  "flame of splendor barakiel": "Rune",
  "immortal savior mardil": "Aden",
  "frintezza": "Goddard",
  "longhorn golkonda": "Aden",
  "nurkas messenger": "Dion",
  "shacram": "Hunters",
  "plague golem": "Goddard",
  "premo prime": "Heine",
  "soul of water ashutar": "Goddard",
  "ember": "Goddard",
  "vanor chief kandra": "Goddard",
  "breka warlock pastu": "Giran",
  "roaring skylancer": "Hunters",
  "ancient weird drake": "Giran",
  "fafurions herald lokness": "Giran",
  "magus kenishee": "Giran",
  "fierce tiger king angel": "Hunters",
  "rotten tree repiro": "Oren",
  "nakondas": "Giran",
  "apepi": "Heine",
  "carnage lord gato": "Oren",
  "thief kelbar": "Hunters",
  "meanas anor": "Aden",
  "katu van leader atui": "Oren",
  "chertuba of great soul": "Gludin",
  "varkas hero shadith": "Goddard",
  "antharas priest cloe": "Giran",
  "langk matriarch rashkos": "Gludin",
  "flamestone golem": "Oren",
  "ghost knight kabed": "Aden",
  "pan dryad": "Dion",
  "flame lord shadar": "Dion",
  "verfa": "Aden",
  "fafurions henchman istary": "Heine",
  "revenant of sir calibus": "Dion",
  "captain of red flag shaka": "Oren",
  "necrosentinel royal guard": "Giran",
  "enchanted forest watcher ruell": "Hunters",
  "biconne of blue sky": "Heine",
  "water couatle ateka": "Heine",
  "vuku grand seer gharmash": "Dion",
  "shadow of halisha a id 25339": "Goddard",
  "sealed evil power sailren": "Rune",
  "gorgolos": "Aden",
  "gigantic chaos golem": "Schuttgart",
  "shadow of halisha d id 25349": "Goddard",
  "soul scavenger": "Gludio",
  "ice fairy sirra": "Schuttgart",
  "fafurions envoy pingolpin": "Heine",
  "icarus sample 1": "Heine",
  "soulless wild boar": "Hunters",
  "tracker leader sharuk": "Gludin",
  "sukar wererat chief": "Gludio",
  "shilens messenger cabrio": "Aden",
  "turek mercenary captain": "Gludin",
  "refugee hopeful leo": "Oren",
  "bandit leader barda": "Oren",
  "leader of cat gang": "Giran",
  "hekaton prime": "Aden",
  "orfens handmaiden": "Oren",
  "queen ant": "Gludio",
  "demon kurikups": "Giran",
  "cats eye bandit": "Dion",
  "korim": "Aden",
  "soul collector acheron": "Dion",
  "tiger king karuta": "Giran",
  "gargoyle lord tiphon": "Aden",
  "timak orc chief ranger": "Oren",
  "ikuntai": "Gludio",
  "shadow of halisha c id 25346": "Goddard",
  "anakim": "Aden",
  "retreat spider cletu": "Hunters",
  "greyclaw kutus": "Gludin",
  "lizardmen leader hellion": "Dion",
  "wizard of storm teruk": "Oren",
  "evas spirit niniel": "Heine",
  "harit hero tamash": "Hunters",
  "corsair captain kylon": "Giran",
  "ketras chief brakki": "Goddard",
  "lord ishka": "Giran",
  "bloody priest rudelto": "Giran",
  "icicle emperor bumbalump": "Goddard",
  "messenger of fairy queen berun": "Hunters",
  "barion": "Aden",
  "elf renoa": "Gludin",
  "stakato queen zyrnna": "Dion",
  "kernon": "Aden",
  "rahha": "Aden",
  "iron giant totem": "Oren",
  "last titan utenus": "Aden",
  "timak seer ragoth": "Oren",
  "evil spirit cyrion": "Hunters",
  "baium": "Aden",
  "princess molrang": "Gludin",
  "sejarrs servitor": "Giran",
  "flamestone giant": "Aden",
  "zakens butcher krantz": "Giran",
  "paniel the unicorn": "Hunters",
  "sorcerer isirr": "Hunters",
  "captain of the ice queens royal guard": "Schuttgart",
  "hestia guardian deity of the hot springs": "Goddard",
  "cursed clara": "Giran",
  "death lord ipos": "Aden",
  "fafurions page sika": "Heine",
  "deadman ereve": "Hunters",
  "palatanos of horrific power": "Aden",
  "mirror of oblivion": "Hunters",
  "ketras commander tayr": "Goddard",
  "cronoss servitor mumu": "Heine",
  "lesser giant olkuth": "Aden",
  "water dragon seer sheshark": "Giran",
  "pagan watcher cerberon": "Oren",
  "spirit of andras the betrayer": "Aden",
  "tirak": "Gludin",
  "earth protector panathen": "Heine",
  "doom blade tanatos": "Aden",
  "grave robber kim": "Aden",
  "leto chief talkin": "Oren",
  "atraiban": "Giran",
  "eilhalder von hellmann": "Rune",
  "demons agent falston": "Rune",
  "beast lord behemoth": "Aden",
  "ghost of the well lidia": "Aden",
  "valakas": "Goddard",
  "kuroboros priest": "Gludin",
  "ragraman": "Gludin",
  "zakens chief mate tillion": "Giran",
  "lilith": "Aden",
  "last lesser giant glaki": "Aden",
  "serpent demon bifrons": "Gludin",
  "road scavenger leader": "Giran",
  "bloody empress decarbia": "Aden",
  "evas guardian millenu": "Heine",
  "king tarlk": "Oren",
  "crazy mechanic golem": "Oren",
  "ketras hero hekaton": "Goddard",
  "black lily": "Giran",
  "furious thieles": "Hunters",
  "guardian of the statue of giant karum": "Aden",
  "knight of destruction gordon": "Goddard",
  "the 3rd underwater guardian": "Heine",
  "tasaba patriarch hellena": "Heine",
  "zaken": "Giran",
  "lord of splendor anays": "Rune",
  "partisan leader talakin": "Dion",
  "kernons faithful servant kelone": "Aden",
  "giant marpanak": "Aden",
  "giant wasteland basilisk": "Gludio",
  "dread avenger kraven": "Oren",
  "ocean flame ashakiel": "Giran",
  "soul of fire nastron": "Goddard",
  "beleths seer sephia": "Giran",
  "captain of queens royal guards": "Dion",
  "gargoyle lord sirocco": "Gludio",
  "triols leader benom": "Rune",
  "andreas van halter": "Rune",
  "last lesser giant olkuth": "Aden",
  "mammon collector talos": "Giran",
  "gran boss sepul": "Goddard",
  "nellis vengeful spirit": "Schuttgart",
  "discarded guardian": "Goddard",
  "gordon": "Goddard",
  "betrayer of urutu freki": "Schuttgart",
  "kaysha herald of icarus": "Schuttgart",
  "dark shaman varangka": "Schuttgart",
  "madness beast": "Gludio",
  "scarlet van halisha": "Goddard",
  "malex herald of dagoniel": "Gludio",
  "boss akata": "Gludio",
  "rayito the looter": "Giran",
  "zombie lord farakelsus": "Gludio"
};
window.CITIES = ['Aden','Giran','Goddard','Rune','Dion','Heine','Oren','Gludio','Gludin','Hunters','Schuttgart'];

/* Bosses ligados a quests / summons / instancias de Interlude */
window.QUEST_BOSSES = {
  "shilens messenger cabrio": 1,
  "death lord hallate": 1,
  "kernon": 1,
  "longhorn golkonda": 1,
  "flame of splendor barakiel": 1,
  "demons agent falston": 1,
  "hestia guardian deity of the hot springs": 1,
  "vanor chief kandra": 1,
  "plague golem": 1,
  "ketras hero hekaton": 1,
  "ketras commander tayr": 1,
  "ketras chief brakki": 1,
  "varkas hero shadith": 1,
  "varkas commander mos": 1,
  "varkas chief horus": 1,
  "andreas van halter": 1,
  "frintezza": 1,
  "scarlet van halisha": 1,
  "anakims nemesis zakaron": 1,
  "queen shyeed": 1,
  "uruka": 1,
  "ember": 1,
  "gordon": 1,
  "discarded guardian": 1,
  "gran boss sepul": 1,
  "immortal savior mardil": 1,
  "shilens priest hisilrome": 1,
  "bloody empress decarbia": 1,
  "meanas anor": 1
};
